make print more obvious

diff --git a/.github/workflows/lint-format.yml b/.github/workflows/lint-format.yml
--- a/.github/workflows/lint-format.yml
+++ b/.github/workflows/lint-format.yml
@@ -35,10 +35,14 @@ jobs:
       - name: Run
         run: wpiformat
       - name: Check output
-        run: git --no-pager diff --exit-code HEAD
-      - name: Print linting docs link
-        if: ${{ failure()}}
-        run: echo "::error ::Linting failed. See https://docs.photonvision.org/en/latest/docs/contributing/linting.html"
+        run: |
+          set +e
+          git --no-pager diff --exit-code HEAD
+          exit_code=$?
+          if test "$exit_code" -ne "0"; then
+            echo "::error ::Linting failed. See https://docs.photonvision.org/en/latest/docs/contributing/linting.html"
+            exit $exit_code
+          fi
       - name: Generate diff
         run: git diff HEAD > wpiformat-fixes.patch
         if: ${{ failure() }}
@@ -59,12 +63,15 @@ jobs:
         with:
           java-version: 17
           distribution: temurin
-      - run: ./gradlew spotlessCheck
+      - run: |
+          set +e
+          ./gradlew spotlessCheck
+          exit_code=$?
+          if test "$exit_code" -ne "0"; then
+            echo "::error ::Linting failed. See https://docs.photonvision.org/en/latest/docs/contributing/linting.html"
+            exit $exit_code
+          fi
         name: Run spotless
-      - name: Print linting docs link
-        if: ${{ failure() }}
-        run: echo "::error ::Linting failed. See https://docs.photonvision.org/en/latest/docs/contributing/linting.html"
-
   client-lint-format:
     name: "PhotonClient Lint and Formatting"
     defaults:
@@ -86,9 +93,20 @@ jobs:
       - name: Install Dependencies
         run: pnpm i --frozen-lockfile
       - name: Check Linting
-        run: pnpm run lint-ci
+        run: |
+          set +e
+          pnpm run lint-ci
+          exit_code=$?
+          if test "$exit_code" -ne "0"; then
+            echo "::error ::Linting failed. See https://docs.photonvision.org/en/latest/docs/contributing/linting.html"
+            exit $exit_code
+          fi
       - name: Check Formatting
-        run: pnpm run format-ci
-      - name: Print linting docs link
-        if: ${{ failure() }}
-        run: echo "::error ::Linting failed. See https://docs.photonvision.org/en/latest/docs/contributing/linting.html"
+        run: |
+          set +e
+          pnpm run format-ci
+          exit_code=$?
+          if test "$exit_code" -ne "0"; then
+            echo "::error ::Linting failed. See https://docs.photonvision.org/en/latest/docs/contributing/linting.html"
+            exit $exit_code
+          fi
